src/components/ChatBox.scss
src/components/ChatBox.tsx
src/components/ChatInput.scss
src/components/ChatInput.tsx
src/components/ChatMessage.scss
src/components/ChatMessage.tsx
src/theme/variables.css
src/utils.tsx

This change was reliant on the change from #55 so I had to pull that branch into this one. I have closed that pull request.

Added message log view for Team/Program Chat

---

src/App.tsx
src/Dashboard.tsx
src/pages/login/login.tsx
src/pages/signup/Signup.tsx

- The login page always appears first when the user launches the app.
- The user can go from login page to signup page and from signup page to login page.
- The user must complete the login before proceeding to the dashboard.
- There are four tabs on the dashboard: tab1, tab2, tab3, and health app integration.

107 page order

---

android/app/capacitor.build.gradle
android/capacitor.settings.gradle
capacitor.config.ts
ios/App/App.xcodeproj/project.pbxproj
ios/App/App/AppDelegate.swift
ios/App/App/GoogleService-Info.plist
ios/App/App/Info.plist
ios/App/Podfile
package-lock.json
package.json
src/firebase.js
src/pages/login/login.tsx
src/pages/signup/Signup.tsx

Fixed all iOS issues. Now everything works on iOS.
- sign up with email and password
- sign up with google
- sign in with email and password
- sign in with google
- successful sign in leads to dashboard (tab1, tab2, tab3, health app integration)
e6d3ec8edd.png)

109 fix ios error

---

package-lock.json

Created the view of the Signup page. No functionality yet besides some placeholder links that will be replaced once there is a forgot password portal. Functionality will be implemented later.
Some screenshots of what was implemented:

14 create view for signup

---

src/App.tsx
src/index.tsx
src/pages/Tab1.tsx
src/pages/login/login.tsx
src/pages/signup/Signup.tsx
src/store/auth-context.tsx

Basics added in. Request to add in to main so that other can use the basics and understand how to use it.

121 implement contextreducer for login information

---

src/components/NavLink.scss
src/components/NavLink.tsx

* Changes navigation links from `<a>` to `<IonItem>` with `href` attribute so they're more Ionic-style
* Fixes popover not closing when mouse leaves

136 fix navigation popover not closing

---

package-lock.json
src/App.tsx
src/Dashboard.tsx
src/components/HomePageMenuItems.tsx
src/components/NavBar.tsx
src/components/loginOrProfileButton.tsx
src/pages/HomePage/HomePage.tsx
src/pages/forgotpassword/forgotpassword.tsx
src/pages/login/login.tsx
src/pages/manualLoggingSteps/manualLoggingSteps.tsx
src/pages/profile/Profile.tsx
src/pages/signup/Signup.tsx
src/pages/stepsCalculator/stepsCalculator.tsx

- Loads profile picture, name, email, join date, and total distance
- Button functionality not implemented yet
- Removed Tab 1, 2, 3
- Successful login will now redirect users to the dashboard, which contains all pages
- The first page to pop up after login will be the Home page
- Users will be able to navigate to other pages such as the Profile page, Manual Steps page, Health App page, Team page, and more from the dashboard

basic profile page functionality & page order fix

---

android/app/capacitor.build.gradle
android/app/src/main/AndroidManifest.xml
package-lock.json
package.json
src/pages/HomePage/HomePage.tsx
src/pages/TeamHome/TeamHome.tsx
src/pages/healthapp/HealthApp.tsx
src/pages/manualLoggingSteps/manualLoggingSteps.tsx
src/pages/profile/Profile.tsx
src/pages/signup/Signup.tsx

Syncs a user's google fit to the user's walktober account and retrieves the step count.

120 google fit

---

src/pages/HomePage/HomePage.tsx

Loads data for displaying up to past 7 days of steps

170 home page (loading past seven days of steps)

---

src/components/NavBar.tsx
src/components/NavLink.scss
src/components/NavLink.tsx

This required rewriting the popover handlers to use a popover controller. Please pull the branch and ensure that the dropdowns work correctly and the links do not log you out.

176 fix navbar logging out

---

src/pages/signup/Signup.tsx
src/pages/signup/signupForm.tsx

Changed the sign in flow to: signup page -> registration question page -> home page and saves the question's answers in the database.
After the signup page, an email verification link is sent to email.

182 new registration process

---

package-lock.json
package.json
src/Dashboard.tsx
src/pages/admin/admin.css
src/pages/admin/admin.tsx

Had to recreate pull request and branch when working on making it work to merge into main.  Currently working on pulling from database to fill out a table.

Admin and announcements

---

src/App.tsx
src/pages/admin/admin.tsx
src/pages/login/login.tsx
src/pages/profile/Profile.tsx
src/store/auth-context.tsx

- sign out button on the profile page
- fixed admin context
- fixed user creation date on the profile page
- basic admin page setup for backend team to take over

198 signout / admin page setup

---

src/pages/healthapp/HealthApp.tsx

- fixed apple health step not loading issue
- now it works well (tested on my phone)

204 apple health step count not loading

---

android/app/capacitor.build.gradle
android/capacitor.settings.gradle
src/pages/healthapp/HealthApp.tsx

Each object in the array stepsByDate represents one day. There should not be multiple objects in the array that represent the same day. Outdated stepsByDate may cause bugs.

193 health app step count and manually entered step count merge

---

src/pages/HomePage/HomePage.css
src/pages/HomePage/HomePage.tsx

added current steps and personal progress

214 main page style changes

---

android/app/capacitor.build.gradle
android/capacitor.settings.gradle
src/App.tsx
src/pages/profile/Profile.tsx
src/store/auth-context.tsx

Now there is a team context. ```ctx.team``` holds team information. (team name which is a unique value)
```ctx``` now has these three fields.
```ctx.user``` , ```ctx.team```, and ```ctx.admin```

221 team context

---

src/pages/admin/admin.tsx

I was asked to fix and switch the date inputs for team deadlines so I swapped them to date inputs instead of date picker modals that didn't work.  also swapped the format slightly to use labels and an input

switched the input for team deadlines

---

src/Dashboard.tsx
src/components/LeaderBoard/LeaderBoardChart.tsx
src/components/NavBar.tsx
src/pages/NewTeamCreation.tsx
src/pages/TeamHome/TeamJoin.tsx
src/pages/profile/Profile.tsx

This is the Team Join Process. If someone doesn't have a team as of yet then when they click team it will take them to the team join page. From there it will show all of the available teams that can be joined. When picking a team, one must input the team name in order to choose the team.

208 team join process

---

src/Dashboard.tsx

Updated navbar icons; added Admin button

---

src/components/ProgressChart.tsx
src/pages/homePage/homePage.tsx

Fixed the steps order and gave it custom colors to ensure visibility.
Will ask backend team to add in the full past 7 days and fill in 0 if there is no data to ensure a full 7 days.

244 fixing minor homepage problems

---

ios/App/App.xcodeproj/project.pbxproj
ios/App/App/Info.plist
src/Dashboard.tsx
src/pages/homePage/homePage.tsx
src/pages/manualLoggingSteps/manualLoggingSteps.tsx
src/pages/profile/profile.tsx
src/pages/teamCreation/teamCreation.tsx
src/pages/teamHome/teamHome.tsx
src/pages/teamHome/teamJoin.tsx

- When the individual step count is updated, the team's total step count and average step count are automatically updated.
- Added a refresher to the profile page, team join page, team profile page, and home page.

256 individual step count update team average step count update

---

src/pages/admin/admin.tsx

Changed the announcement module to "create open team" module, and implemented the functionality. Admin creates an open team where it's set to public and its an empty team.

236 admin - create open team is replacing announcement module 

---

src/components/LeaderBoard/LeaderBoardChart.scss
src/components/LeaderBoard/LeaderBoardChart.tsx

Placement numbers added to the leaderboard, and made styling adjustments too. Will be fixing sizing of chart based on size of screen in another branch.

Alissa add placement numbers to leaderboard

---

src/pages/admin/admin.tsx
src/pages/homePage/homePage.tsx
src/pages/manualLoggingSteps/manualLoggingSteps.tsx
src/pages/profile/profile.tsx
src/pages/teamHome/teamHome.tsx
src/pages/teamHome/teamJoin.tsx

Starting now, real-time updates will be applied to the homepage, profile page, steps log page, team join page, and team profile page.
- The homepage, profile page, and steps log page will update when there is a database update for the corresponding user.
- The team join page will update when there is a database update for any team (addition, deletion, or update).
- The team profile page will update when there is a database update for the corresponding team (when a team member joins, leaves, or there is an update to the steps log).

Real time updates

---

src/pages/admin/admin.tsx
src/store/admin-context.tsx

added table for team info under the user table, added in two settings in the user page, one for the start of walktober and and one for the end.  these and the information for the reports need to be synced into the back end

added team table, walktober duration user settings

---

src/pages/login/login.css
src/pages/login/login.tsx

Login screen enter key now fires the login button

[292] Add login button press with 'enter' key

---

package-lock.json
package.json
src/components/NavBar.tsx
src/components/NavLink.tsx

Adds an About link to the desktop navbar that opens the Walktober page on pdx.edu.

Add about link to desktop navbar

---

src/Dashboard.tsx
src/ProtectedRoutes.tsx
src/pages/healthApp/healthApp.tsx
src/pages/homePage/homePage.tsx
src/pages/manualLoggingSteps/manualLoggingSteps.tsx
src/pages/profile/profile.tsx
src/pages/teamCreation/teamCreation.tsx
src/pages/teamHome/teamHome.tsx
src/pages/teamHome/teamJoin.tsx

- Implemented routes protection (check auth state when routing)
- Removed manual auth check in all pages

implemented protected routes and removed manual auth check in all pages

---

src/pages/admin/admin.tsx

added total average steps column to team table

---

src/pages/profile/profile.tsx

Added leaf functionality to the profile page. To access the color, do "stepLogs.color"

229: leaf functionality in profile

---

src/components/LeaderBoard/LeaderBoardChart.tsx

User can now easily see where they are on the leaderboard.
Before joining team
After joining team

Leaderboard user highlight

---

src/pages/teamHome/teamHome.scss
src/pages/teamHome/teamHome.tsx

added styling

---

src/pages/manualLoggingSteps/manualLoggingSteps.css
src/pages/manualLoggingSteps/manualLoggingSteps.tsx

Manual steps logging page styling

---

src/components/progChart.css

made the chart not disappear when playing an acordian with the screen width.

make the chart not disappear

---

src/components/CalendarLeafs.tsx
src/pages/manualLoggingSteps/manualLoggingSteps.css
src/pages/profile/profile.css
src/pages/profile/profile.tsx

323 update profile page for the leafs data

---

src/components/ProgressChart.tsx
src/pages/homePage/homePage.css
src/pages/homePage/homePage.tsx

I wrapped up some of the last few things that needed changing on the home page: 
- Somehow the order of the cards got messed up so I fixed that 
- Removed the progress bar
- Removed the badges 
- Adjusted leaderboard height

Tweak home page

---

src/components/LeaderBoard/LeaderBoardChart.scss
src/components/LeaderBoard/LeaderBoardChart.tsx
src/components/LeaderBoard/TeamLeaderboardChart.scss
src/components/LeaderBoard/TeamLeaderboardChart.tsx

Made the leaderboard title larger, and fixed overlapping profile pictures.

Minor fixes

---

src/pages/teamCreation/teamCreation.tsx

Titles kinda says it all. the commits that were done for teamCreation to add the channel id were removed so I re-added the code assign a channel id the team when its created

Readded the channel id additions to teamCreation

---

src/pages/homePage/homePage.tsx
src/pages/teamHome/teamHome.tsx
src/theme/app.scss

Fixed padding on Discord widgets so it doesn't have border

---

src/pages/manualLoggingSteps/manualLoggingSteps.tsx

Fixed the dates that were shown on the step log

344 debug pt2

---

src/pages/adminSteps/adminSteps.css
src/pages/adminSteps/adminSteps.tsx

copy pasta of manual steps styling

---

package-lock.json
src/pages/manualLoggingSteps/manualLoggingSteps.tsx

Added time constraints to health app sync.
If today is before the event start date, a toast message "event is not started yet" is prompted, and no sync would be performed.
If today is between the event start date and the event end date, it will retrieve the data from the event start date to today.
If today is after the event end date, it will retrieve the data from the event start date to the event end date.

317 debugging

---

src/components/CalendarLeafs.css
src/pages/profile/profile.css
src/pages/profile/profile.tsx

some padding added, change font sizes and leafs given certain sizes

---

src/pages/login/login.css
src/pages/login/login.tsx

- Aligned password show button with password input box 
- Changed the clickable icon to a button to make it more accessible

Fixed password show button bug

---

src/components/CalendarLeafs.css
src/components/CalendarLeafs.tsx
src/pages/homePage/homePage.css
src/pages/homePage/homePage.tsx
src/pages/login/login.tsx
src/pages/profile/profile.css
src/pages/profile/profile.tsx
src/theme/app.scss

Oh boy. I have done so many different things in this PR:
- Moved leaves to right side of calendar numbers so that the calendar numbers stay aligned 
- Added tiny screen css for calendar for Galaxy Fold 
- Changed links to dark green
- Took out badges from profile page 
- Took our personal goal from profile page 
- Fixed giant profile picture bug 
- Changed alt text on calendar leaves

Clean up profile page

---

src/pages/admin/admin.tsx

This is such a tiny change and I meant to do it in the last PR and I'm kicking myself that I didn't.

Add commas to large numbers

---

package-lock.json
src/pages/adminSteps/adminSteps.tsx

I have added the correction in the dates for the admin edit step logs, as requested. Here is the evidence that it works:
(CHECK OUT THE USER'S NAME. IYKYK)
Closes #366

366 admin step log corrected date

---

src/pages/404landing/landing404.css
src/pages/404landing/landing404.tsx

Cosmetic changes to 404

---

src/pages/teamHome/teamJoin.tsx

I changed the team join page so that it will still show teams that are full but it will not allow you to join them.

Show teams that are full 

---

src/pages/admin/admin.css
src/pages/admin/admin.tsx

- Settings now show current value 
- Team table now shows privacy status

Tweak admin page

---

src/pages/teamHome/teamHome.scss
src/pages/teamHome/teamHome.tsx

- Fixed the phone view for the team home page

Fix phone view on team home page 

---

src/Dashboard.tsx

Rearranged nav bar

---

src/pages/healthApp/healthApp.css
src/pages/healthApp/healthApp.tsx

Styled the health app integration page

Style health app integration

---

src/pages/teamHome/teamHome.scss
src/pages/teamHome/teamHome.tsx

Ayeeeee, Got them changes for the team password changes. Now the team leader of a private team can change the password for the team. The input fields must be filled, and must be the same obviously. If the user clicks outside the modal it will close it, but they will need to click the button to open 2 times to get it back open.

Implemented them team password changes

---

src/pages/signup/signup.tsx

Removed the email verification email being sent to the user. Also deleted one console.log

Removed the email verification link when signing up.

---

src/pages/teamHome/teamHome.scss
src/pages/teamHome/teamHome.tsx

- Removed some css that was forcing the text to be white in light mode 
- Changed modal height to auto 
- Changed eye clickable icons to buttons

Fix view of team password change modal

---

src/pages/profile/newPassword.css
src/pages/profile/newPassword.tsx

Styled password change page

---

src/pages/admin/admin.css

- Fixed the admin zebra striping so that its visible in dark mode

Fixed admin zebra striping
